version: '3'
services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
      REDIS_HOST: redis
      REDIS_DB: 0
      # NODE_ENV: 'production'
    volumes:
      - .:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql
      - redis

  redis:
    image: redis

  mysql:
    image: mysql:8.0.26
    command: mysqld --default-authentication-plugin=mysql_native_password
    # volumes:
      # - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    ports:
      - '3306:3306'
